<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MIklanKoran extends Model
{
    use HasFactory;
    public $table = 'iklan_koran';
    public $timestamps = false;
    protected $fillable =[
        'nik',
        'no_order',	
        'k_order',
        'k_biro',
        'k_klien',
        'atasnama',
        'j_atasnama',
        'k_produk_old',
        'k_sproduk_old',	
        'k_sales_old',	
        'k_indus',
        'judul',
        'k_jenis',
        'k_rubrik',	
        'k_tarif',
        'warna',	
        'hal',
        'jmuat',
        'jkolom',
        'jtinggi',
        'jtarif',
        'tarif',
        'tharga',
        'discp_in',
        'discr_in',	
        'nharga',	
        'ppnp',
        'ppnr',
        'materai',
        'ttagih',
        'discp_out',
        'discr_out',	
        'tgl_inv',
        'tgl_jt',
        'noseri',
        'tgl_pajak',
        'sts_pajak',
        'trs_pajak',	
        'type',
        'sts_barter',	
        'flag_btl',
        'tgl_input',
        'jam_input',
        'user_input',
        'note',
        'flag_update',
        'jam_update',
        'tgl_update',
        'user_update',
        'cara_bayar',	
        'validasi',
        'stat_validasi',
        'ket_validasi',
        'user_validasi',
        'tgl_validasi',
        'jam_validasi',
        'flag_paket_lama',
        'ket_paket',
        'petugas',
        'k_produk',
        'k_sproduk',	
        'k_sales',
        'flag_protect',	
        'flag_revisi',
        'nik_asal',
        'ket_revisi',
        'k_grup_old',	
        'k_grup',
        'tagihan_bermasalah',	
        'keterangan_bermasalah'
    ]; 
}


// 'nik',
// 'no_order',	
// 'k_order',
// 'k_biro',
// 'k_klien',
// 'atasnama',
// 'j_atasnama',
// 'k_produk_old',
// 'k_sproduk_old',	
// 'k_sales_old',	
// 'k_indus',
// 'judul',
// 'k_jenis',
// 'k_rubrik',	
// 'k_tarif',
// 'warna',	
// 'hal',
// 'jmuat',
// 'jkolom',
// 'jtinggi',
// 'jtarif',
// 'tarif',
// 'tharga',
// 'discp_in',
// 'discr_in',	
// 'nharga',	
// 'ppnp',
// 'ppnr',
// 'materai',
// 'ttagih',
// 'discp_out',
// 'discr_out',	
// 'tgl_inv',
// 'tgl_jt',
// 'noseri',
// 'tgl_pajak',
// 'sts_pajak',
// 'trs_pajak',	
// 'type',
// 'sts_barter',	
// 'flag_btl',
// 'tgl_input',
// 'jam_input',
// 'user_input',
// 'note',
// 'flag_update',
// 'jam_update',
// 'tgl_update',
// 'user_update',
// 'cara_bayar',	
// 'validasi',
// 'stat_validasi',
// 'ket_validasi',
// 'user_validasi',
// 'tgl_validasi',
// 'jam_validasi',
// 'flag_paket_lama',
// 'ket_paket',
// 'petugas',
// 'k_produk',
// 'k_sproduk',	
// 'k_sales',
// 'flag_protect',	
// 'flag_revisi',
// 'nik_asal',
// 'ket_revisi',
// 'k_grup_old',	
// 'k_grup',
// 'tagihan_bermasalah',	
// 'keterangan_bermasalah'





      
  
       
  
 

